### ISSUE TITLE
Error 400: You have not specified an ack ID in the request

### ISSUE THREAD

**Issue by gbmeuk** [logstash-plugins/logstash-input-google_pubsub#14]
We've recently had an issue where we started to see many of these errors in the logs and causing Pub/Sub Hich acknowledgement invalid error counts. After engaging with Google's Pub/Sub team we were able to determine that the pub/sub plugin is sending an acknowledgement, even if there are 0 messages to acknowledge in the pull request.

I'm afraid I don't know Ruby well but my expectation is that there is a function to check the size/length of a map, so I believe that adding a condition around https://github.com/logstash-plugins/logstash-input-google_pubsub/blob/master/lib/logstash/inputs/google_pubsub.rb#L268-L274 which only calls the acknowledgement API if it is > 0, will fix this issue.

**Comment by lukepereira** [comment]
I am also seeing this error in my logstash logs. I have yet to receive any logs from the plugin and I'm wondering if it's because of this error or if you are still able to receive logs while getting this error.

**Comment by gbmeuk** [comment]
Hi @lukepereira, we are processing logs, so maybe there is some other underlying issue that you have.

**Comment by amrmotan** [comment]
Hi, 

I started facing this issue recently. Not sure what is going wrong. Also logs are not sent to Elasticsearch.

**Comment by danbiwer** [comment]
I'm also seeing this error and receiving logs.

**Comment by josephlewis42** [comment]
Closing, the fix has been released in `1.0.6` as part of #25 

The plugin can be updated with the following command
```
bin/logstash-plugin update logstash-input-google_pubsub
```
