### ISSUE TITLE
SSLError : certificate verify failed

### ISSUE THREAD

**Issue by scorsi** [logstash-plugins/logstash-input-google_pubsub#17]
Hi,

I already saw #10 and the linked stackoverflow issue.

I'm running on Ubuntu 16.04 LTS. The only things installed is Nginx, Elastic, Kibana and Logstash with pubsub plugin.

My env var :
```
SSL_CERT_FILE=/usr/share/logstash/logstash-core/lib/logstash/certs/cacert.pem
```
I also tried `/usr/local/etc/openssl/cert.pem`.

I'm running logstash (for test) with the following cmd `sudo bin/logstash -f /etc/logstash/conf.d/`.

The stack error:
```
$ sudo bin/logstash -f /etc/logstash/conf.d/
WARNING: Could not find logstash.yml which is typically located in $LS_HOME/config or /etc/logstash. You can specify the path using --path.settings. Continuing using the defaults
Could not find log4j2 configuration at path /usr/share/logstash/config/log4j2.properties. Using default config which logs errors to the console
[ERROR] 2018-02-08 10:03:44.960 [[main]<google_pubsub] pipeline - A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::GooglePubSub project_id=>"something-valid", topic=>"something-valid", subscription=>"something-valid", codec=><LogStash::Codecs::JSON id=>"json_e5fb8aec-6273-4a2e-b134-3b13bbcd0024", enable_metri
c=>true, charset=>"UTF-8">, id=>"63111eb4b716e43252c47ad685f4e357656f425cf1bc051d8bc691d8cbf30de8", enable_metric=>true, max_messages=>5>
  Error: certificate verify failed
  Exception: Faraday::SSLError
  Stack: org/jruby/ext/openssl/SSLSocket.java:228:in `connect_nonblock'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/net/http.rb:938:in `connect'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/net/http.rb:868:in `do_start'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/net/http.rb:857:in `start'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/net/http.rb:1409:in `request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/signet-0.8.1/lib/signet/oauth_2/client.rb:967:in `fetch_access_token'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/signet-0.8.1/lib/signet/oauth_2/client.rb:1005:in `fetch_access_token!'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/googleauth-0.5.1/lib/googleauth/signet.rb:69:in `fetch_access_token!'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_pubsub-1.0.4/lib/logstash/inputs/google_pubsub.rb:154:in `request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_pubsub-1.0.4/lib/logstash/inputs/google_pubsub.rb:216:in `run'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:524:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:517:in `block in start_input'
```

My logstash plugin configuration
```
$ cat /etc/logstash/conf.d/*
input {
    google_pubsub {
        project_id => "something-valid"
        topic => "something-valid"
        subscription => "something-valid"
        codec => json
    }
}
output {
  elasticsearch {
    hosts => ["localhost:9200"]
    template_name => "something-valid"
    index => "something-valid-%{+YYYY.MM.dd}"
  }
  stdout { codec => json }
}
```

My logstash configuration at `/etc/logstash/logstash.yml` is basic (I can give it if necessary), but logstash seems not founding it (see the first warning of the stack).

Here's what's in the `/etc/logstash` folder.
```
$ l -R /etc/logstash/
/etc/logstash/:
total 24
drwxrwxr-x 2 logstash logstash 4096 Feb  2 10:30 conf.d
-rw-r--r-- 1 logstash logstash 1738 Jan 10 04:07 jvm.options
-rw-r--r-- 1 logstash logstash 1334 Jan 10 04:07 log4j2.properties
-rw-r--r-- 1 logstash logstash 6426 Feb  2 09:35 logstash.yml
-rw-r--r-- 1 logstash logstash 1659 Jan 10 04:07 startup.options

/etc/logstash/conf.d:
total 8
-rw-r--r-- 1 logstash logstash 184 Feb  2 10:30 00-input.conf
-rw-r--r-- 1 logstash logstash 185 Feb  2 09:26 02-output.conf
```

Thanks for your help.

Sylvain

**Comment by scorsi** [comment]
I fixed the warning by append `--path.settings /etc/logstash` to my cmd (which is weird because it is the default value).

But this don't fix the SSLError.

**Comment by jakelandis** [comment]
It doesn't appear that this plugin supports configurable trust stores, so the certificate trust is likely java's default location. `<path to jre>/lib/security/cacerts`.  You can find out exactly where by setting this flag in the jvm.options `-Djavax.net.debug=SSL,trustmanager` , it will echo out the path to the log/stdout. 

You can add your own certs to the default with the key tool. For example https://docs.microsoft.com/en-us/azure/java-add-certificate-ca-store 

I am going to close this issue, but feel free to open an enhancement to allow this plugin to be configured to point to a custom trust store.

**Comment by scorsi** [comment]
I think I've fixed the error by giving the access of `/var/lib/logstash` `/etc/logstash` and `/usr/share/logstash` to the user and group `logstash`. Because they initialy belonged to `root`.

**Comment by andrelucasti** [comment]
Hi guys, i've the same problem 

# cat google-pubsub.conf 
input {
	google_pubsub {
		project_id => "pub-sub-test-193913"
		topic => "measure_device"
		subscription => "pull_measure_device"
		json_key_file => "/home/andrelucastic/key2.json"
		max_messages => "50"
	}

}

output {
  elasticsearch {
  		 hosts => localhost
  		 index => google_pubsub
  		 document_type => measure_device
  		
	}
  #stdout { codec => rubydebug }
}


someone help me pls ?

**Comment by andrelucasti** [comment]
my log 

  Error: certificate verify failed
  Exception: Faraday::SSLError
  Stack: org/jruby/ext/openssl/SSLSocket.java:228:in `connect_nonblock'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:938:in `connect'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:868:in `do_start'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:857:in `start'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1409:in `request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/signet-0.8.1/lib/signet/oauth_2/client.rb:967:in `fetch_access_token'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/signet-0.8.1/lib/signet/oauth_2/client.rb:1005:in `fetch_access_token!'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_pubsub-1.0.4/lib/logstash/inputs/google_pubsub.rb:154:in `request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_pubsub-1.0.4/lib/logstash/inputs/google_pubsub.rb:216:in `run'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:516:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:509:in `block in start_input'

**Comment by scorsi** [comment]
Hi, 

Did you check for the right access as I said in my last message? Did you append the path settings in your command line?

Sylvain

**Comment by andrelucasti** [comment]
Yes @scorsi i userd the command `sudo -u logstash ./logstash -f /etc/logstash/conf.d/google-pubsub.conf --path.settings=/etc/logstash`

but continue the same problem =/


[2018-04-06T12:35:27,470][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::GooglePubSub project_id=>"pub-sub-test-193913", topic=>"measure_device", subscription=>"pull_measure_device", json_key_file=>"/home/andrelucastic/key.json", max_messages=>50, codec=><LogStash::Codecs::JSON id=>"json_f2da218d-cacf-4910-ae4f-519fe7de32e8", enable_metric=>true, charset=>"UTF-8">, id=>"171d356a879402e4888300c0b18369ab188eb7d913fbcb507db61d5726f845d1", enable_metric=>true>
  Error: certificate verify failed
  Exception: Faraday::SSLError
  Stack: org/jruby/ext/openssl/SSLSocket.java:228:in `connect_nonblock'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:938:in `connect'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:868:in `do_start'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:857:in `start'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1409:in `request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/signet-0.8.1/lib/signet/oauth_2/client.rb:967:in `fetch_access_token'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/signet-0.8.1/lib/signet/oauth_2/client.rb:1005:in `fetch_access_token!'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_pubsub-1.0.4/lib/logstash/inputs/google_pubsub.rb:154:in `request'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_pubsub-1.0.4/lib/logstash/inputs/google_pubsub.rb:216:in `run'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:516:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:509:in `block in start_input'
