### ISSUE TITLE
Retain attributes from messages

### ISSUE THREAD

**Issue by mijamo** [logstash-plugins/logstash-input-google_pubsub#7]
I noticed that this import plugin just ignores all the attributes set in the pub/sub message.

Would it be possible to keep them with the same key/values through a simple mapping, like this old plugin did: https://github.com/Wondermall/logstash-input-google-cloud-pubsub/blob/a6c9bece8e432a56972805944d14a4dbfd3fbbdf/lib/logstash/inputs/google_cloud_pubsub.rb#L82 ?

It would be very VERY useful to be able to use that plugin in an efficient and sustainable way.

I would have made a pull request myself by I'm afraid my Ruby skills are inexistent.

**Comment by josephlewis42** [comment]
@mijamo would adding a flag like "include_attributes" work for you? 

If turned off then the plugin would work as it does today with the deserialized data being top-level, but if it's turned on the output would look something like this:

```json
{
  "attributes": {"attr1":"val1", "attr2":"val2"},
  "data": {"foo":42, "bar":[1,2,3]}
}
```

**Comment by andyshinn** [comment]
I think related to this, I'd like to have access to other attributes in the response such as `message_id`. Maybe the the option could just return the JSON just like a normal Pub/Sub message does? I'm expecting something like this:

```
{
  "message": {
    "attributes": {
      "key": "value"
    },
    "data": "SGVsbG8gQ2xvdWQgUHViL1N1YiEgSGVyZSBpcyBteSBtZXNzYWdlIQ==",
    "message_id": "136969346945"
  },
  "subscription": "projects/myproject/subscriptions/mysubscription"
}
```

At the very least, getting `message_id` to use as the `document_id` helps with deduplication.
