### ISSUE TITLE
Output to pub/sub?

### ISSUE THREAD

**Issue by acasademont** [logstash-plugins/logstash-input-google_pubsub#8]
Would it be possible to also have pub/sub output? Should it be a different plugin?

**Comment by acchen97** [comment]
@acasademont yes it would be separate. Feel free to file an issue for this in the Logstash main repository for this. Also, PRs are very welcome if you're open to contributing!

**Comment by ScottBrenner** [comment]
+1.

As there isn't yet a direct way to output to pub/sub, can anyone suggest a "creative" way to do it?

**Comment by NirKamara** [comment]
Hi,

I created a plugin for it.
You can get it [here](https://github.com/NirKamara/logstash-output-google-cloud-pubsub).

**Comment by josephlewis42** [comment]
I have a Google-contributed one going through final review/approval now, so optimistically I could have gems out for to beta-test as soon as next week. 

If you head over to [the repo](https://github.com/logstash-plugins/logstash-output-google_pubsub) and subscribe to [this issue](https://github.com/logstash-plugins/logstash-output-google_pubsub/issues/1), I'll keep you all updated over there. Once things are tested and look good we can work with @acchen97 to get it fully merged.
